version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-eb: circleci/aws-elastic-beanstalk@1.0.2
jobs:
  ready:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Ready
          command: |
            npm run frontend:ready
      - run:
          name: Back-End Ready
          command: |
            npm run backend:ready
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
    workflows:
      - docker:
      - ready:
          filters:
            branches:
              only:
                - main